pool:
  vmImage: 'Ubuntu 16.04'

steps:
- checkout: self
  fetchDepth: 10
  
- task: NodeTool@0
  inputs:
    versionSpec: '6.10'
  displayName: 'Install Node.js'

- script: |
    npm install -g npm@latest
  displayName: 'npm latest'
  
- script: |
    npm install -g grunt-cli
  displayName: 'grunt-cli'
  
- script: |
    npm ci
  displayName: 'npm ci'

- script: |
    npm test
  displayName: 'npm test'
